### ISSUE TITLE
NotImplementedError in jax

### ISSUE THREAD

**Issue by turczyneq** [RadostW/stochastic#12] opened 2024-10-23 15:38 UTC
While running test on github after pushing, code that was working well in past now raises an error:

`   /opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/pychastic/sde_solver.py:275: DeprecationWarning: jax.tree_map is deprecated: use jax.tree.map (jax v0.4.25 or newer) or jax.tree_util.tree_map (any JAX version).
    jax.tree_map(lambda x: jnp.reshape(x,(-1,chunk_size)+x.shape[1:]), wiener_integrals)` 

`FAILED tests/test_trajectories.py::test_probability_at_x - NotImplementedError: jax.experimental.host_callback has been deprecated since March 2024 and is now no longer supported. See https://github.com/jax-ml/jax/issues/20385`
 
I have imported _pychastic_ on my computer previously and it is still working, just new installations of pychastic are raising this error.

**Comment by RadostW** [comment] 2024-10-23 16:18
This is caused by a backwards compatibility breaking changes in `jax`. Required small changes to migrate. 

Fixed with 20707851d839559b2ce5b3f4e1e2917b01f23928
Minor reworks for compatibility with python 3.8 and pypi upload finished with a7146c52df05a9df70cb2245ca57d17d9e53e328

**Closed by RadostW** 2024-10-23 16:18 UTC
